const labels = {
  en: {
    profile:'Profile', caregiver:'Caregiver', active:'Active', caregiverId:'CAREGIVER ID', email:'EMAIL',
    settings:'APP SETTINGS', edit:'Edit Profile', changePhoto:'Change photo', uploadPhoto:'Upload Photo', name:'Name', firstName:'First name',
    lastName:'Last name', phone:'Phone number', changePhone:'Change phone number', phoneNote:'A verification SMS will be sent to the new number.',
    code:'6-digit verification code', sendCode:'Send code', verifyPhone:'Verify new number', language:'Language',
    notification:'Notification Preferences', notificationSub:'Queue alerts and updates',
    accessibility:'Accessibility & Text Size', display:'Display preferences', privacy:'Privacy & Security',
    privacySub:'Account and privacy settings', logout:'Log Out', save:'Save Changes', cancel:'Cancel',
    english:'English', sinhala:'සිංහල', tamil:'தமிழ்',
    appQueue:'App queue alerts', smsQueue:'SMS queue alerts', threshold:'Queue alert threshold',
    thresholdNote:'Used when queue notification services support individual thresholds.',
    smsNote:'SMS preference is saved; actual SMS delivery depends on the shared queue notification service.',
    mandatoryNote:'Essential account and consent alerts remain available for safety.',
    textSize:'Text size', small:'Small', medium:'Medium', large:'Large', highContrast:'High contrast',
    privacyCaregiver:'Allow caregiver access', privacyQueue:'Show queue details',
    privacyNote:'These preferences are stored. Server-side access enforcement must be completed with your team before treating them as privacy controls.',
    emailNote:'Email editing requires a separate verification flow and is currently read-only.',
    profileSaved:'Profile updated successfully.', photoSaved:'Profile photo updated.',
    phoneSaved:'Phone number verified and updated.', codeSent:'Code requested. Check the new phone number.',
    required:'Please enter both your first and last name.',
    upload:'Uploading...', saving:'Saving...', close:'Close', currentPhone:'Current phone', chooseLanguage:'Choose your preferred language'
  },
  si: {
    profile:'පැතිකඩ', caregiver:'රැකබලා ගන්නා', active:'සක්‍රීය', caregiverId:'රැකබලා ගන්නා අංකය', email:'විද්‍යුත් තැපෑල',
    settings:'යෙදුම් සැකසුම්', edit:'පැතිකඩ සංස්කරණය', changePhoto:'ඡායාරූපය වෙනස් කරන්න', uploadPhoto:'ඡායාරූපයක් උඩුගත කරන්න', name:'නම', firstName:'මුල් නම',
    lastName:'වාසගම', phone:'දුරකථන අංකය', changePhone:'දුරකථන අංකය වෙනස් කරන්න', phoneNote:'නව අංකයට සත්‍යාපන SMS පණිවිඩයක් යවනු ලැබේ.',
    code:'ඉලක්කම් 6ක සත්‍යාපන කේතය', sendCode:'කේතය යවන්න', verifyPhone:'නව අංකය තහවුරු කරන්න', language:'භාෂාව',
    notification:'දැනුම්දීම් සැකසුම්', notificationSub:'පෝලිම් දැනුම්දීම්',
    accessibility:'ප්‍රවේශය සහ අකුරු ප්‍රමාණය', display:'දර්ශන සැකසුම්', privacy:'පෞද්ගලිකත්වය සහ ආරක්ෂාව',
    privacySub:'ගිණුම සහ ආරක්ෂාව', logout:'ඉවත් වන්න', save:'වෙනස්කම් සුරකින්න', cancel:'අවලංගු කරන්න',
    english:'English', sinhala:'සිංහල', tamil:'தமிழ்',
    appQueue:'යෙදුමේ පෝලිම් දැනුම්දීම්', smsQueue:'SMS පෝලිම් දැනුම්දීම්', threshold:'පෝලිම් අනතුරු ඇඟවීමේ සීමාව',
    thresholdNote:'පුද්ගලික සීමා සඳහා සේවාව සහාය දක්වන විට මෙය භාවිතා වේ.',
    smsNote:'SMS මනාපය සුරකිනු ඇත; පණිවිඩ යැවීම සේවාව මත රඳා පවතී.',
    mandatoryNote:'අත්‍යවශ්‍ය ගිණුම් සහ අවසර දැනුම්දීම් පවතී.',
    textSize:'අකුරු ප්‍රමාණය', small:'කුඩා', medium:'මධ්‍යම', large:'විශාල', highContrast:'ඉහළ වෙනස',
    privacyCaregiver:'රැකබලා ගන්නාට ප්‍රවේශය ලබා දෙන්න', privacyQueue:'පෝලිම් විස්තර පෙන්වන්න',
    privacyNote:'මෙම මනාප සුරකිනු ලැබේ. සේවාදායක ආරක්ෂාව කණ්ඩායම සමඟ සම්පූර්ණ කළ යුතුය.',
    emailNote:'විද්‍යුත් තැපෑල වෙනස් කිරීමට වෙනම සත්‍යාපනයක් අවශ්‍ය වේ.',
    profileSaved:'පැතිකඩ යාවත්කාලීන විය.', photoSaved:'ඡායාරූපය යාවත්කාලීන විය.',
    phoneSaved:'දුරකථන අංකය තහවුරු කර යාවත්කාලීන විය.', codeSent:'කේතය යවා ඇත. නව දුරකථනය පරීක්ෂා කරන්න.',
    required:'මුල් නම සහ වාසගම ඇතුළත් කරන්න.', upload:'උඩුගත වෙමින්...', saving:'සුරකිමින්...', close:'වසන්න', currentPhone:'වත්මන් දුරකථනය', chooseLanguage:'ඔබේ භාෂාව තෝරන්න'
  },
  ta: {
    profile:'சுயவிவரம்', caregiver:'பராமரிப்பாளர்', active:'செயலில்', caregiverId:'பராமரிப்பாளர் எண்', email:'மின்னஞ்சல்',
    settings:'செயலி அமைப்புகள்', edit:'சுயவிவரத்தைத் திருத்து', changePhoto:'புகைப்படத்தை மாற்று', uploadPhoto:'புகைப்படம் பதிவேற்று', name:'பெயர்', firstName:'முதல் பெயர்',
    lastName:'குடும்பப் பெயர்', phone:'தொலைபேசி எண்', changePhone:'தொலைபேசி எண்ணை மாற்று', phoneNote:'புதிய எண்ணுக்கு சரிபார்ப்பு SMS அனுப்பப்படும்.',
    code:'6 இலக்க சரிபார்ப்புக் குறியீடு', sendCode:'குறியீட்டை அனுப்பு', verifyPhone:'புதிய எண்ணைச் சரிபார்', language:'மொழி',
    notification:'அறிவிப்பு விருப்பங்கள்', notificationSub:'வரிசை அறிவிப்புகள் மற்றும் புதுப்பிப்புகள்',
    accessibility:'அணுகல் மற்றும் எழுத்துரு அளவு', display:'காட்சி விருப்பங்கள்', privacy:'தனியுரிமை மற்றும் பாதுகாப்பு',
    privacySub:'கணக்கு மற்றும் தனியுரிமை அமைப்புகள்', logout:'வெளியேறு', save:'மாற்றங்களைச் சேமி', cancel:'ரத்து செய்',
    english:'English', sinhala:'සිංහල', tamil:'தமிழ்',
    appQueue:'செயலி வரிசை அறிவிப்புகள்', smsQueue:'SMS வரிசை அறிவிப்புகள்', threshold:'வரிசை அறிவிப்பு வரம்பு',
    thresholdNote:'தனிப்பட்ட வரம்புகளை சேவை ஆதரிக்கும் போது பயன்படுத்தப்படும்.',
    smsNote:'SMS விருப்பம் சேமிக்கப்படும்; அனுப்புதல் பகிரப்பட்ட சேவையைப் பொறுத்தது.',
    mandatoryNote:'அத்தியாவசிய கணக்கு மற்றும் ஒப்புதல் அறிவிப்புகள் தொடர்ந்து கிடைக்கும்.',
    textSize:'எழுத்து அளவு', small:'சிறியது', medium:'நடுத்தரம்', large:'பெரியது', highContrast:'அதிக மாறுபாடு',
    privacyCaregiver:'பராமரிப்பாளர் அணுகலை அனுமதி', privacyQueue:'வரிசை விவரங்களைக் காட்டு',
    privacyNote:'இந்த விருப்பங்கள் சேமிக்கப்படுகின்றன. சேவையக அணுகல் விதிகளை உங்கள் குழு செயல்படுத்த வேண்டும்.',
    emailNote:'மின்னஞ்சல் மாற்ற தனி சரிபார்ப்பு தேவை.',
    profileSaved:'சுயவிவரம் புதுப்பிக்கப்பட்டது.', photoSaved:'புகைப்படம் புதுப்பிக்கப்பட்டது.',
    phoneSaved:'தொலைபேசி எண் சரிபார்க்கப்பட்டு மாற்றப்பட்டது.', codeSent:'குறியீடு அனுப்பப்பட்டது. புதிய தொலைபேசியைச் சரிபார்க்கவும்.',
    required:'முதல் பெயர் மற்றும் குடும்பப் பெயரை உள்ளிடவும்.', upload:'பதிவேற்றுகிறது...', saving:'சேமிக்கிறது...', close:'மூடு', currentPhone:'தற்போதைய எண்', chooseLanguage:'விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்'
  }
};
export default labels;
